# Generated by Django 2.2.1 on 2019-05-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yut',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
