# Generated by Django 2.2.1 on 2019-05-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yut', '0003_auto_20190503_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yut',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
