# Generated by Django 2.2.1 on 2019-05-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yut', '0004_auto_20190503_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yut',
            name='name',
            field=models.TextField(default='None', max_length=100),
        ),
    ]
