# Generated by Django 2.2.1 on 2019-05-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yut', '0005_auto_20190503_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=100)),
                ('move_value', models.IntegerField()),
                ('x_coor', models.IntegerField()),
                ('y_coor', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='yut',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
