# Generated by Django 2.2.1 on 2019-05-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yut', '0006_auto_20190503_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horse',
            old_name='move_value',
            new_name='move_val',
        ),
    ]
