# Generated by Django 2.2.1 on 2019-05-03 16:07

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('yut', '0008_auto_20190503_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_coor', jsonfield.fields.JSONField()),
            ],
        ),
    ]
