# Generated by Django 2.2.1 on 2019-05-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yut', '0009_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
